version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prism
      MYSQL_USER: prism
      MYSQL_PASSWORD: prism
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql+pymysql://prism:prism@db:3306/prism
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_MINUTES: 10080
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
